# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker_test_db;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту BogomoloffPD@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      -BogomoloffPD@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="377ba733-67a2-46d0-b259-7c90c9feca5a"